services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - default
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - default
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
