services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - default
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - default
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - default
